### ISSUE TITLE
Project Demonstration Timetable

### ISSUE THREAD

**Issue by DoreenM** [pembeci/ceng3507#1]
Hi,

I did not receive the doodle for choosing the exam dates. Is it possiple to get it?

**Comment by pembeci** [comment]
You didn't receive it since it didn't exist up until now. Thanks for reminding me. You can find it [here](http://doodle.com/poll/n3965yf52zpaquvz). I also added some slots for early (1st week) demos, so you don't need to e-mail me if that's what you prefer.
