### ISSUE TITLE
'Download'

### ISSUE THREAD

**Issue by cenktrms** [pembeci/ceng3507#2]
Merhaba hocam,
Databasede file type (upload) ını kullanarak itemlerin imagelerini db ye upload ettim. Çağırırkende "  src="{{=URL('download', args=jet.img)}}  " bu şekillde kullandım ve çok düzgün bi şekilde çalıştı. Fakat "User Authentication" yaptıktan sonra ( User Authentication u sizin gösterdiğiniz şekilde yaptım.) Bir şekilde  "download" a erişimi durdurdu ve imageleri göstermemeye başladı 

Bu şekilde bi hata verdi : 

![capture3](https://cloud.githubusercontent.com/assets/15123025/11912800/b65eddb0-a656-11e5-966c-a1ae3952f79b.PNG)
![capture1](https://cloud.githubusercontent.com/assets/15123025/11912801/b6601e96-a656-11e5-8d33-39bd17f89f33.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15123025/11912802/b6624b62-a656-11e5-84a8-a4f4be303947.PNG)

Sanırım Kodumda bir çakışma var. Nerede bi çakışma olabileceği hakkında bi fikriniz varmı hocam?

Yada bu sorunu yaşayıp çözen arkadaşlar varsa ve banada anlatırsa çok sevinirim.

İyi günler iyi çalışmalar.

**Comment by cenktrms** [comment]
Tamam hocam Download fonksiyonumda hata varmış hallettim teşekkürler iyi çalışmalar

**Comment by pembeci** [comment]
In these kind of situations, just copy the image src from the produced page and try to open it standalone (i.e. in a new tab). This way, you can test if the problem is with the download function or something else.
